# colors
set -g default-terminal "tmux-256color"
set-option -a terminal-features 'xterm-256color:RGB'

set -g history-limit 1000000
set -g mouse on
set -g base-index 1
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -g renumber-windows on   # renumber all windows when any window is closed
set -g set-clipboard on      # use system clipboard
set -g status-interval 3     # update the status bar every 3 seconds
set -g status-style 'bg=default' # transparent
unbind C-b
set -g prefix C-a

# Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

#Bindings
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"
unbind v
bind v copy-mode
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt (cmd+w)
bind P paste-buffer
source ~/.config/tmux/utility.conf
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'niksingh710/minimal-tmux-status'
# Plugins Settings
set -g @yank_action 'copy-pipe-and-cancel'
set -g @minimal-tmux-bg "#6A9589"
set -g @minimal-tmux-indicator-str "  "
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'
run '~/.tmux/plugins/tpm/tpm'

