bind-key -N "⌘+k sesh session picker" "T" run-shell "~/.config/bin/sesh_start"
bind-key -N "⌘+⇧+K sesh picker (alias)" "G" display-popup -w 90% -h 80% -E "sesh picker --icons --hide-duplicates --preview"

bind -N "⌘+g lazygit" g new-window -c "#{pane_current_path}" -n " LazyGit" "lazygit 2> /dev/null"
bind -N "⌘+i pr status" i run-shell "~/.config/tmux/pr-status.sh"
bind -N "⌘+⇧+U worktree panel" W run-shell "~/.config/tmux/worktree-panel.sh"
bind -N "⌘+⇧+G gh-dash" z new-window -c "#{pane_current_path}" -n "󰊤  GHDash" "gh dash 2> /dev/null"
bind -N "⌘+⇧+M lazysql" m new-window -c "#{pane_current_path}" -n "󰆼 LazySql" "lazysql 2> /dev/null"
bind -N "⌘+l last-session (via sesh)" L run-shell "sesh last || tmux display-message -d 1000 'Oops, no last sessions found'"
bind -N "⌘+e editor" e new-window -S -n ' Nvim' 'nvim +GoToFile'
bind -N "⌘+⇧+E editor diff" E new-window -S -n ' Nvim Diff' 'nvim +CodeDiff'
bind -N "⌘+⇧+D resume session" A new-window -c "#{pane_current_path}" -n "󰘦  Claude" "ccr --here"
bind -N "⌘+⇧+Z claude yolo" Z new-window -c "#{pane_current_path}" -n "󰚩  Claude" "cldy"
bind -N "⌘+a claude" a new-window -c "#{pane_current_path}" -n "󰘦  Claude" "claude"
bind -N "⌘+b commit message" S new-window -c "#{pane_current_path}" -n "󰊢 Commit Message Generating" "aimsg"
bind -N "⌘+n split vertical" '%' split-window -c '#{pane_current_path}' -h
bind -N "⌘+⇧+' split horizontal" '"' split-window -c '#{pane_current_path}'
bind -N "⌘+t new window" c new-window -c '#{pane_current_path}'
bind-key -N "⌘+⇧+A claude session picker" "C" run-shell "~/.config/tmux/claude-sesh.sh"
bind -N "⌘+⇧+S next claude pane needing attention" j run-shell "~/.config/tmux/claude-next.sh"
bind -N "⌘+⇧+B toggle status bar" b set -g status

