bind-key -N "⌘+k sesh session picker" "T" run-shell "sesh connect \"$(
  sesh list --icons --hide-duplicates| fzf-tmux -p 100%,100% --reverse \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^w worktree ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-w:change-prompt(🌿  )+reload(git -C "$WORK_MAIN" worktree list --porcelain | grep ^worktree | cut -d\" \" -f2 | tail -n +2)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:70%' \
    --preview 'sesh preview {}' \
)\""
bind-key -N "⌘+⇧+K sesh picker (alias)" "G" display-popup -w 90% -h 80% -E "sesh picker --icons --hide-duplicates --preview"

bind -N "⌘+g lazygit" g new-window -c "#{pane_current_path}" -n " LazyGit" "lazygit 2> /dev/null"
bind -N "⌘+⇧+G gh-dash" z new-window -c "#{pane_current_path}" -n "󰊤  GHDash" "gh dash 2> /dev/null"
bind -N "⌘+⇧+M lazysql" m new-window -c "#{pane_current_path}" -n "󰆼 LazySql" "lazysql 2> /dev/null"
bind -N "⌘+l last-session (via sesh)" L run-shell "sesh last || tmux display-message -d 1000 'Oops, no last sessions found'"
bind -N "⌘+e editor" e new-window -S -n ' Nvim' 'nvim +GoToFile'
bind -N "⌘+⇧+E editor diff" E new-window -S -n ' Nvim Diff' 'nvim +CodeDiff'
bind -N "⌘+⇧+D resume session" A new-window -c "#{pane_current_path}" -n "󰘦  Claude" "ccr --here"
bind -N "⌘+⇧+Z claude yolo" Z new-window -c "#{pane_current_path}" -n "󰚩  Claude" "cldy"
bind -N "⌘+a claude" a new-window -c "#{pane_current_path}" -n "󰘦  Claude" "claude"
bind -N "⌘+b commit message" S new-window -c "#{pane_current_path}" -n "󰊢 Commit Message Generating" "aimsg"
bind -N "⌘+n split vertical" '%' split-window -c '#{pane_current_path}' -h
bind -N "⌘+⇧+' split horizontal" '"' split-window -c '#{pane_current_path}'
bind -N "⌘+t new window" c new-window -c '#{pane_current_path}'
bind-key -N "⌘+⇧+A claude session picker" "C" run-shell "~/.config/tmux/claude-sesh.sh"
bind -N "⌘+⇧+S next claude pane needing attention" j run-shell "~/.config/tmux/claude-next.sh"
bind -N "⌘+⇧+B toggle status bar" b set -g status

